# Generated by Django 4.2 on 2023-05-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_alter_post_body'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_publish_bb7600_idx',
            old_name='blog_pos_publish_d5dc96_idx',
        ),
    ]
